import {
  index,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  date,
} from "drizzle-orm/pg-core";

import { accounts } from "./accounts.js";

/**
 * Operations — append-only ledger of user-recorded portfolio actions.
 *
 * Phase 4a (cost basis port): the table exists in the legacy DB. We add
 * the TS surface so the worker can read it and the server can accept
 * `POST /operations` batches when the importer ports over.
 *
 * `legacy_id` is a stable client-side identifier (UUID generated by the
 * old single-user app at the moment of entry) so re-imports are
 * idempotent — `(account_id, legacy_id)` is the natural key.
 *
 * Money fields use `numeric` to keep precision through cost-basis math.
 * Drizzle returns them as strings — repository layer parses to Number
 * (or BigDecimal in the cost-basis port, TBD in Phase 4c).
 */
export const opTypeEnum = pgEnum("op_type", [
  "buy",
  "sell",
  "swap",
  "transfer",
  "deposit",
  "withdraw",
  "fee",
  "open",
  "close",
  "loan",
  "loan_repay",
  "loan_take",
  "div",
  "other",
]);

export const opSourceEnum = pgEnum("op_source", [
  "manual",
  "import",
  "promoted",
]);

export const fundsKindEnum = pgEnum("funds_kind", ["own", "loan"]);

export const operations = pgTable(
  "operations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    legacyId: text("legacy_id").notNull(),
    accountId: uuid("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    date: date("date").notNull(),
    type: opTypeEnum("type").notNull(),
    source: opSourceEnum("source").notNull().default("manual"),
    fromName: text("from_name"),
    toName: text("to_name"),
    cur1: text("cur1"),
    amount1: numeric("amount1", { precision: 38, scale: 18 }),
    cur2: text("cur2"),
    amount2: numeric("amount2", { precision: 38, scale: 18 }),
    rate: numeric("rate", { precision: 28, scale: 8 }),
    avgPrice: numeric("avg_price", { precision: 28, scale: 8 }),
    priceUsd: numeric("price_usd", { precision: 28, scale: 8 }),
    posType: text("pos_type"),
    funds: fundsKindEnum("funds"),
    loanRate: numeric("loan_rate", { precision: 28, scale: 8 }),
    loanRateTake: numeric("loan_rate_take", { precision: 28, scale: 8 }),
    loanFromName: text("loan_from_name"),
    loanPosLegacyId: text("loan_pos_legacy_id"),
    loanLtv: numeric("loan_ltv", { precision: 28, scale: 8 }),
    loanLiqPct: numeric("loan_liq_pct", { precision: 28, scale: 8 }),
    loanLiqPrice: numeric("loan_liq_price", { precision: 28, scale: 8 }),
    loanCollateralUsd: numeric("loan_collateral_usd", {
      precision: 28,
      scale: 8,
    }),
    network: text("network"),
    commissionNetwork: text("commission_network"),
    closeTokenAmount: numeric("close_token_amount", {
      precision: 38,
      scale: 18,
    }),
    direction: text("direction"),
    comment: text("comment").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    uniqueIndex("operations_account_legacy_uq").on(
      table.accountId,
      table.legacyId
    ),
    index("operations_account_date_idx").on(table.accountId, table.date),
    index("operations_type_idx").on(table.type),
  ]
);

export type OperationRow = typeof operations.$inferSelect;
export type NewOperationRow = typeof operations.$inferInsert;
export type OpType = OperationRow["type"];
export type OpSource = OperationRow["source"];
export type FundsKind = NonNullable<OperationRow["funds"]>;
